Added support for planar motion using interactive markers.
ridgeback/ridgeback pull request #20
Opened 2017-06-21 19:10 UTC by tonybaltovski

Valid in kinetic, see https://github.com/ros-visualization/interactive_marker_twist_server/commit/28a9730d3eac96e719dfd9463ca9d69441493714.

2017-06-21 19:19 UTC, mikepurvis commented on ridgeback_control/launch/teleop.launch
> +  <arg name="config" value="planar" />
Consider:

    <arg name="config" default="planar" />

Which will allow it to be overridden.

2017-06-21 19:19 UTC, mikepurvis commented on ridgeback_control/launch/teleop.launch
> +    <rosparam command="load" file="$(find interactive_marker_twist_server)/config/$(arg config).yaml" />
Might want to use `config/teleop_$(arg config).yaml` since this package has lots of different config files in it.

2017-06-21 19:20 UTC, mikepurvis commented on ridgeback_control/launch/teleop.launch
> +    <rosparam command="load" file="$(find interactive_marker_twist_server)/config/$(arg config).yaml" />
Also, you probably meant to commit the new `yaml` file too, right?

2017-06-21 19:37 UTC, tonybaltovski commented on ridgeback_control/launch/teleop.launch
> +    <rosparam command="load" file="$(find interactive_marker_twist_server)/config/$(arg config).yaml" />
I meant to use the `planar.yaml` from `interactive_marker_twist_server` as is.

2017-06-21 19:38 UTC, tonybaltovski commented on ridgeback_control/launch/teleop.launch
> +  <arg name="config" value="planar" />
Agreed.

2017-06-21 19:53 UTC, mikepurvis commented on ridgeback_control/launch/teleop.launch
> +    <rosparam command="load" file="$(find interactive_marker_twist_server)/config/$(arg config).yaml" />
Oh whoops, totally missed that you were reaching across to another package.

2017-06-21 19:53 UTC, mikepurvis commented
LGTM.

2017-06-21 20:07 UTC, tonybaltovski commented
Travis is failing due to https://github.com/ros-visualization/interactive_marker_twist_server/pull/10.

2017-06-21 20:11 UTC, TheDash commented
For verbosity:

"FAILURE:

```

[/root/catkin_ws/src/ridgeback/ridgeback_control/launch/teleop.launch]:


	error loading <rosparam> tag: 


	file does not exist [/opt/ros/kinetic/share/interactive_marker_twist_server/config/planar.yaml]


XML is <rosparam command="load" file="$(find interactive_marker_twist_server)/config/$(arg config).yaml"/>

```

In which I believe Tony is fixing that w/ above PR. Merge can go through when fix goes through

2017-06-22 21:23 UTC, UltronDestroyer requested changes
Fixes must be approved and deployed for interactive markers in order to pass travis, which is required to merge into kinetic-devel. A rebase must also be done since author history was fixed

2018-02-13 14:46 UTC, closed without merging